### ISSUE TITLE
Implement date comparison for recycle date results.

### ISSUE THREAD

**Issue by zo0o0ot** [zo0o0ot/AppletonPebble#9]
Use date comparison to help determine if local results are old or new, and check if new results are needed.

**Comment by zo0o0ot** [comment]
Related to #8.

**Comment by zo0o0ot** [comment]
Apparently, PebbleJS supports MomentJS natively.

http://stackoverflow.com/questions/31722514/date-formatting-and-manipulation-in-pebblejs

http://momentjs.com/docs/

This seems like the way to implement comparison.

**Comment by zo0o0ot** [comment]
Since I'm working off the master, I'm going to upload this as a gist:
https://gist.github.com/zo0o0ot/a19e0d43a0143f0e8c11

I'm having issues getting MomentJS to work, since it's in the vendor directory and Clock imports it.  I'm trying to use it through Clock.

[PHONE] pebble-app.js:?: [PHONESIM] [WARNING] Exception decoding QemuInboundPacket.footer
[PHONE] pebble-app.js:?: (+) [window 1] : [window 1]
[PHONE] pebble-app.js:?: Saved Recycle Day is: Tuesday, 08-11-2015
[PHONE] pebble-app.js:?: JavaScript Error:
TypeError: undefined is not a function
    at Object.loader (app.js:62:26)
    at Object.loader.require (loader.js:44:10)
    at require (loader.js:41:48)
[PHONE] pebble-app.js:?: [PHONESIM] [WARNING] Exception decoding QemuInboundPacket.footer

**Comment by zo0o0ot** [comment]
I tweeted to PebbleDev and CloudPebble to verify I'm not crazy.

https://twitter.com/rosslarsonWI/status/630375773682044928

**Comment by zo0o0ot** [comment]
I was able to figure out the date comparison and upload the code to this repo.  It's not yet in the Pebble appstore, but the app now compares the date before hitting the Appleton API for a new result.
